import type { Metadata } from "next";
import "../globals.css";
import { Locale, routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
   title: "SkillMatch",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
   params,
}: Readonly<{
   children: React.ReactNode;
   params: Promise<{ locale: string }>;
}>) {
   const { locale } = await params;

   // Ensure that the incoming `locale` is valid
   if (!routing.locales.includes(locale as Locale)) {
      notFound();
   }

   // Providing all messages to the client
   const messages = await getMessages();

   // Determine direction
   const direction = locale === "ar" ? "rtl" : "ltr";
   return (
      <html lang={locale} dir={direction}>
         <body
            className={direction === "rtl" ? "font-arabic-sans" : "font-sans"}>
            <NextIntlClientProvider locale={locale} messages={messages}>
               {children}
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
